services:
  restaurant-reservation.api:
    image: restaurant-reservation.api
    build:
      context: .
      dockerfile: RestaurantReservation.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=db;Database=RestaurantReservationDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;
      - DatabaseSettings__LogLevel=Information
      - DatabaseSettings__EnableSensitiveDataLogging=false
    ports:
      - "5056:8080"
      - "7279:8081"
    depends_on:
      - db
    networks:
      - restaurant-network

  restaurant-reservation.api.auth:
    image: restaurant-reservation.api.auth
    build:
      context: .
      dockerfile: RestaurantReservation.Api.Auth/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=db;Database=RestaurantReservationDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;
      - DatabaseSettings__LogLevel=Information
      - DatabaseSettings__EnableSensitiveDataLogging=false
    ports:
      - "5241:8080"
      - "7040:8081"
    depends_on:
      - db
    networks:
      - restaurant-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  dbdata: