services:
  restaurant-reservation.api:
    image: restaurant-reservation.api
    build:
      context: .
      dockerfile: RestaurantReservation.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5056:8080"
      - "7279:8080"