services:
  migrate:
    image: restaurant-reservation.migrate
    build:
      context: ./RestaurantReservation.Migrate
      dockerfile: Dockerfile
    environment:
      - DatabaseSettings__ConnectionString=Server=db;Database=RestaurantReservationDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;
    depends_on:
      - db
    networks:
      - restaurant-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  dbdata:
